server:
  port: 8888
spring:
  application:
    name: blog-admin
  mvc:
    servlet:
      path: /api

  #数据库的配置
  # datasource
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://******?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=true
    username: root
    password: *****

  servlet:
    multipart:
      max-request-size: 20MB
      max-file-size: 2MB
  redis:
    port: 6379
    host: ******
    password: ******
    database: 1


#mybatis-plus
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      table-prefix: ms_
  mapper-locations: classpath:com/liu/blog2/mapper/xml/*.xml


qiniu:
  accessKey: ********
  accessSecretKey: ********

rocketmq:
  producer:
    group: blog_group
    topic:
  name-server: *********
